import {
  attribute,
  autoGeneratedHashKey,
  table,
  hashKey
} from '@aws/dynamodb-data-mapper-annotations';

import {JsonObject, JsonProperty} from "json2typescript";

//const uuidV4 = require('uuid/v4');

@table('wx_user')
@JsonObject
export class User {
  @autoGeneratedHashKey() 
  @hashKey()
  @JsonProperty("id", String)
  id: string;

  @attribute() 
  @JsonProperty("email", String)
  email?: string;

  @attribute() 
  @JsonProperty("password", String)
  password?: string;

  // @rangeKey({defaultProvider: () => new Date()})
  // @JsonProperty("createdAt", Date)
  // createdAt: Date;

  public copyInto(json: string) : User {    
    let jsonUser: User = JSON.parse(json);
    console.log(jsonUser);
    let user : User = new User();
    user.email = jsonUser.email;
    user.password = jsonUser.password;
    user.id = jsonUser.id;

    return user;
  }

}
