import {
  attribute,
  autoGeneratedHashKey,
  table,
} from '@aws/dynamodb-data-mapper-annotations';
//const uuidV4 = require('uuid/v4');

@table('wx_user')
export class User {
  @autoGeneratedHashKey() id: string;

  @attribute() email?: string;

  @attribute() password?: string;
}
