import {
  attribute,
  autoGeneratedHashKey,
  table,
} from '@aws/dynamodb-data-mapper-annotations';

import {JsonObject, JsonProperty, JsonConvert} from "json2typescript";

//const uuidV4 = require('uuid/v4');

@table('wx_user')
@JsonObject
export class User {
  @autoGeneratedHashKey() 
  @JsonProperty("id", String)
  id: string;

  @attribute() 
  @JsonProperty("email", String)
  email?: string;

  @attribute() 
  @JsonProperty("password", String)
  password?: string;

  public copyInto(json: Object) : User {
    //var user: User = deserialize(User, json);
    //let jsonObj: object = JSON.parse(json);
    let jsonConvert: JsonConvert = new JsonConvert();
    let user: User = jsonConvert.deserializeObject(json, User);
    console.log(user);
    return user;
  }

}
